// The Origin of this file is generated by Google Gemini Flash
// https://share.gemini.google/8QoquVYFXBWj

import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:sqflite/sqflite.dart';
import '../../models/place_photo.dart';
import '../../services/database_service.dart';
import '../widgets/album_photo_viewer.dart';

class DatabaseExplorerScreen extends StatefulWidget {
  const DatabaseExplorerScreen({super.key});

  @override
  State<DatabaseExplorerScreen> createState() => _DatabaseExplorerScreenState();
}

class _DatabaseExplorerScreenState extends State<DatabaseExplorerScreen> {
  Database? _db;

  List<String> _tables = [];
  String? _selectedTable;

  List<Map<String, dynamic>> _rows = [];
  List<String> _columns = [];
  Map<String, bool> _columnIsBlob = {};
  Map<String, String> _columnTypes = {};
  Map<String, bool> _columnIsProtected = {};
  Map<String, bool> _columnIsPrimaryKey = {};
  Map<String, bool> _columnIsForeignKey = {};
  Map<String, bool> _columnIsOtherKey = {};
  String? _primaryKey;

  // Pagination / Chunk Loading
  int _currentOffset = 0;
  final int _chunkSize = 30;
  bool _hasMore = true;
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _initializeDatabase().then((_) => _loadTables());
  }

  Future<void> _initializeDatabase() async {
    _db = await DatabaseService.instance.database;
  }

  Future<void> _loadTables() async {
    try {
      if (_db == null) return;
      List<Map<String, dynamic>> tables = await DatabaseService.instance
          .getExplorerTables();

      setState(() {
        _tables = tables.map((row) => row['name'] as String).toList();
        if (_tables.isNotEmpty) {
          _selectedTable = _tables.first;
          _resetAndLoadTableData(_selectedTable!);
        }
      });
    } catch (e) {
      _showSnackBar("Fehler beim Laden der Tabellen: $e");
    }
  }

  Future<void> _resetAndLoadTableData(String tableName) async {
    setState(() {
      _selectedTable = tableName;
      _rows = [];
      _columns = [];
      _currentOffset = 0;
      _hasMore = true;
    });
    await _loadTableInfo(tableName);
    await _loadMoreData();
  }

  void _openViewer(List<PlacePhoto> photos, int index) {
    Navigator.of(context).push(
      MaterialPageRoute<void>(
        builder: (_) => AlbumPhotoViewer(
          photos: photos,
          initialIndex: index,
          onChanged: () => {},
          deleteEnabled: () => false,
        ),
      ),
    );
  }

  Future<void> _loadTableInfo(String tableName) async {
    if (_db == null) return;
    try {
      List<Map<String, dynamic>> pragma = await DatabaseService.instance
          .getExplorerTableInfo(tableName);

      String? pkColumn;
      List<String> cols = [];
      Map<String, String> types = {};
      Map<String, bool> isBlob = {};
      Map<String, bool> isProtected = {};
      Map<String, bool> isPrimaryKey = {};
      Map<String, bool> isForeignKey = {};
      Map<String, bool> isOtherKey = {};

      for (var col in pragma) {
        String colName = col['name'];
        String colType = col['type'] ?? '';

        cols.add(colName);
        types[colName] = colType;
        isBlob[colName] = colType.toLowerCase() == 'blob';
        isPrimaryKey[colName] = col['pk'] == 1;
        isForeignKey[colName] = colName.endsWith('_uuid');
        isOtherKey[colName] = colName.endsWith('_id');
        isProtected[colName] =
            isBlob[colName] == true ||
            isPrimaryKey[colName] == true ||
            isForeignKey[colName] == true ||
            isOtherKey[colName] == true;

        if (col['pk'] == 1) {
          pkColumn = colName;
        }
      }

      setState(() {
        _columns = cols;
        _columnTypes = types;
        _columnIsBlob = isBlob;
        _columnIsPrimaryKey = isPrimaryKey;
        _columnIsForeignKey = isForeignKey;
        _columnIsOtherKey = isOtherKey;
        _columnIsProtected = isProtected;
        _primaryKey = pkColumn;
      });
    } catch (e) {
      _showSnackBar("Fehler beim Laden der Tabellen-Struktur: $e");
    }
  }

  Future<void> _loadMoreData() async {
    if (_isLoading || !_hasMore || _selectedTable == null) return;

    setState(() => _isLoading = true);

    try {
      if (_db == null) return;

      List<Map<String, dynamic>> newRows = await DatabaseService.instance
          .getExplorerTableRows(
            _selectedTable!,
            offset: _currentOffset,
            limit: _chunkSize,
          );

      setState(() {
        _rows.addAll(
          newRows.map((row) => Map<String, dynamic>.from(row)).toList(),
        );
        _currentOffset += _chunkSize;
        if (newRows.length < _chunkSize) {
          _hasMore = false;
        }
      });
    } catch (e) {
      _showSnackBar("Fehler beim Laden der Daten: $e");
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _updateCell(
    String column,
    dynamic oldValue,
    int rowIndex,
  ) async {
    if (_primaryKey == null) {
      _showSnackBar("Update nicht möglich: Kein Primary Key definiert!");
      return;
    }

    final rowData = _rows[rowIndex];
    final pkValue = rowData[_primaryKey];

    if (pkValue == null) {
      _showSnackBar("Update nicht möglich: Primary Key dieser Zeile ist null!");
      return;
    }

    TextEditingController controller = TextEditingController(
      text: oldValue?.toString() ?? "",
    );

    // Typbestimmung anhand des echten Spaltentyps aus der DB
    final columnType = _columnTypes[column]?.toUpperCase() ?? '';
    final isNumeric =
        columnType.contains('INT') ||
        columnType.contains('NUM') ||
        columnType.contains('REAL');

    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text("Feld bearbeiten: $column"),
        content: TextField(
          controller: controller,
          decoration: const InputDecoration(labelText: "Neuer Wert"),
          keyboardType: isNumeric
              ? const TextInputType.numberWithOptions(decimal: true)
              : TextInputType.text,
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text("Abbrechen"),
          ),
          ElevatedButton(
            onPressed: () async {
              dynamic newValue = controller.text;

              // Parsing basierend auf dem DB-Spaltentyp (fängt auch NULL-Konvertierungen ab)
              if (columnType.contains('INT')) {
                newValue = int.tryParse(controller.text) ?? oldValue;
              } else if (columnType.contains('REAL') ||
                  columnType.contains('NUM')) {
                newValue = double.tryParse(controller.text) ?? oldValue;
              }

              try {
                await DatabaseService.instance.updateExplorerTableRow(
                  _selectedTable!,
                  {column: newValue},
                  '$_primaryKey = ?',
                  [pkValue],
                );

                if (!mounted) return;
                setState(() {
                  _rows[rowIndex][column] = newValue;
                });

                if (mounted) Navigator.pop(context);
                _showSnackBar("Datenbank aktualisiert!");
              } catch (e) {
                _showSnackBar("Fehler beim Speichern: $e");
              }
            },
            child: const Text("Speichern"),
          ),
        ],
      ),
    );
  }

  void _showSnackBar(String message) {
    if (!mounted) return;
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(SnackBar(content: Text(message)));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('SQLite DB Explorer'),
        backgroundColor: Colors.teal,
      ),
      body: SafeArea(
        child: Column(
          children: [
            // DROPDOWN-BEREICH
            Padding(
              padding: const EdgeInsets.all(12.0),
              child: Row(
                children: [
                  const Text(
                    "Tabelle: ",
                    style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(width: 10),
                  Expanded(
                    child: DropdownButton<String>(
                      value: _selectedTable,
                      isExpanded: true,
                      items: _tables.map((String table) {
                        return DropdownMenuItem<String>(
                          value: table,
                          child: Text(table),
                        );
                      }).toList(),
                      onChanged: (String? newValue) {
                        if (newValue != null) {
                          _resetAndLoadTableData(newValue);
                        }
                      },
                    ),
                  ),
                ],
              ),
            ),
            const Divider(height: 1),

            // TABELLEN-INHALT (Horizontal + Vertikal Scroll)
            Expanded(
              child: _columns.isEmpty
                  ? const Center(
                      child: Text("Keine Daten oder keine Tabelle ausgewählt"),
                    )
                  : SingleChildScrollView(
                      scrollDirection: Axis.vertical,
                      child: SingleChildScrollView(
                        scrollDirection: Axis.horizontal,
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            DataTable(
                              headingRowColor: WidgetStateProperty.all(
                                Colors.grey[200],
                              ),
                              columns: _columns.map((col) {
                                final isPk = _columnIsPrimaryKey[col] == true;
                                final isFk = _columnIsForeignKey[col] == true;
                                final typeStr =
                                    _columnTypes[col] != null &&
                                        _columnTypes[col]!.isNotEmpty
                                    ? " <${_columnTypes[col]}>"
                                    : "";

                                return DataColumn(
                                  label: Text(
                                    isPk
                                        ? "$col 🔑"
                                        : isFk
                                        ? "$col 🔗$typeStr"
                                        : "$col$typeStr",
                                    style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      color: isPk
                                          ? Colors.teal
                                          : isFk
                                          ? Colors.teal.shade900
                                          : Colors.black,
                                    ),
                                  ),
                                );
                              }).toList(),
                              rows: List.generate(_rows.length, (rowIndex) {
                                final rowData = _rows[rowIndex];

                                return DataRow(
                                  cells: _columns.map((colName) {
                                    final isBlob =
                                        _columnIsBlob[colName] == true;
                                    final isProtected =
                                        _columnIsProtected[colName] == true;
                                    final isPrimaryKey =
                                        _columnIsPrimaryKey[colName] == true;
                                    final isForeignKey =
                                        _columnIsForeignKey[colName] == true;
                                    final isOtherKey =
                                        _columnIsOtherKey[colName] == true;

                                    // Variablen sauber INNERHALB des Spalten-Mappings deklariert
                                    Uint8List? bytes;
                                    Widget? imageWidget;

                                    if (isBlob) {
                                      bytes = rowData[colName] as Uint8List?;
                                      try {
                                        if (bytes != null && bytes.isNotEmpty) {
                                          imageWidget = Image.memory(
                                            bytes,
                                            width: 80,
                                            height: 45,
                                            fit: BoxFit.contain,
                                          );
                                        } else {
                                          imageWidget = const Icon(
                                            Icons.broken_image,
                                            size: 20,
                                            color: Colors.grey,
                                          );
                                        }
                                      } catch (e) {
                                        imageWidget = const Icon(
                                          Icons.error,
                                          size: 20,
                                          color: Colors.red,
                                        );
                                      }
                                    }

                                    final cellValue = isBlob
                                        ? "<BLOB>"
                                        : rowData[colName];

                                    return DataCell(
                                      !isBlob
                                          ? Text(
                                              cellValue?.toString() ?? 'NULL',
                                              style: TextStyle(
                                                fontWeight: isPrimaryKey
                                                    ? FontWeight.bold
                                                    : FontWeight.normal,
                                                fontStyle:
                                                    cellValue == null ||
                                                        isProtected
                                                    ? FontStyle.italic
                                                    : FontStyle.normal,
                                                color: cellValue == null
                                                    ? Colors.grey
                                                    : isProtected ||
                                                          isPrimaryKey ||
                                                          isBlob
                                                    ? Colors.green
                                                    : isForeignKey
                                                    ? Colors.teal.shade500
                                                    : isOtherKey
                                                    ? Colors.green.shade900
                                                    : Colors.black,
                                              ),
                                            )
                                          : Padding(
                                              padding:
                                                  const EdgeInsets.symmetric(
                                                    vertical: 4.0,
                                                  ),
                                              child: ClipRRect(
                                                borderRadius:
                                                    BorderRadius.circular(6),
                                                child: imageWidget,
                                              ),
                                            ),
                                      showEditIcon: !isProtected,
                                      onTap: !isProtected
                                          ? () => _updateCell(
                                              colName,
                                              cellValue,
                                              rowIndex,
                                            )
                                          : isBlob &&
                                                bytes != null &&
                                                bytes.isNotEmpty
                                          ? () {
                                              final photo = PlacePhoto(
                                                photoData: bytes!,
                                              );
                                              _openViewer([photo], 0);
                                            }
                                          : null,
                                    );
                                  }).toList(),
                                );
                              }),
                            ),

                            // CHUNK LOADER BUTTON
                            Padding(
                              padding: const EdgeInsets.all(16.0),
                              child: Row(
                                children: [
                                  if (_hasMore)
                                    ElevatedButton.icon(
                                      onPressed: _isLoading
                                          ? null
                                          : _loadMoreData,
                                      icon: _isLoading
                                          ? const SizedBox(
                                              width: 16,
                                              height: 16,
                                              child: CircularProgressIndicator(
                                                strokeWidth: 2,
                                              ),
                                            )
                                          : const Icon(Icons.arrow_downward),
                                      label: const Text("Mehr Zeilen laden..."),
                                    )
                                  else
                                    const Text(
                                      "--- Ende der Tabelle erreicht ---",
                                      style: TextStyle(color: Colors.grey),
                                    ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
            ),
          ],
        ),
      ),
    );
  }
}
