// The Origin of this file is generated by Google Gemini Flash
// https://share.gemini.google/8QoquVYFXBWj
// Prompt:
// Ich bräuchte für meine Flutter app mit sqflite einen einfachen Datenbank explorer screen.
// Also eine Seite mit einem Dropdown ganz oben für die Tabellen.
// Darunter den Inhalt der Tabelle mit einem Chunk Loader und vertikal und horizontal scroll.
// Wenn möglich, als Sahnehäubchen noch die Felder editierbar.

import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:sqflite/sqflite.dart';

import '../../services/database_service.dart';

class DatabaseExplorerScreen extends StatefulWidget {
  const DatabaseExplorerScreen({super.key});

  @override
  State<DatabaseExplorerScreen> createState() => _DatabaseExplorerScreenState();
}

class _DatabaseExplorerScreenState extends State<DatabaseExplorerScreen> {
  Database? _db;

  List<String> _tables = [];
  String? _selectedTable;

  List<Map<String, dynamic>> _rows = [];
  List<String> _columns = [];
  Map<String, bool> _columnIsBlob = {};
  Map<String, String> _columnTypes = {};
  Map<String, bool> _columnIsProtected = {};
  Map<String, bool> _columnIsPrimaryKey = {};
  Map<String, bool> _columnIsForeignKey = {};
  Map<String, bool> _columnIsOtherKey = {};
  String? _primaryKey;

  // Pagination / Chunk Loading
  int _currentOffset = 0;
  final int _chunkSize = 30;
  bool _hasMore = true;
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _initializeDatabase().then((_) => _loadTables());
  }

  Future<void> _initializeDatabase() async {
    _db = await DatabaseService.instance.database;
  }

  // 1. Alle Tabellennamen aus der SQLite-Metatabelle abfragen
  Future<void> _loadTables() async {
    try {
      if (_db == null) return;
      List<Map<String, dynamic>> tables = await DatabaseService.instance
          .getExplorerTables();

      setState(() {
        _tables = tables.map((row) => row['name'] as String).toList();
        if (_tables.isNotEmpty) {
          _selectedTable = _tables.first;
          _resetAndLoadTableData(_selectedTable!);
        }
      });
    } catch (e) {
      _showSnackBar("Fehler beim Laden der Tabellen: $e");
    }
  }

  // Setzt den Chunk-Loader zurück, wenn die Tabelle gewechselt wird
  Future<void> _resetAndLoadTableData(String tableName) async {
    setState(() {
      _selectedTable = tableName;
      _rows = [];
      _columns = [];
      _currentOffset = 0;
      _hasMore = true;
    });
    await _loadTableInfo(tableName);
    await _loadMoreData();
  }

  // Schema der Tabelle auslesen (Spaltennamen & Primary Key)
  Future<void> _loadTableInfo(String tableName) async {
    if (_db == null) return;
    try {
      // Spalten auslesen
      List<Map<String, dynamic>> pragma = await DatabaseService.instance
          .getExplorerTableInfo(tableName);

      String? pkColumn;
      List<String> cols = [];
      Map<String, String> types = {};
      Map<String, bool> isBlob = {};
      Map<String, bool> isProtected = {};
      Map<String, bool> isPrimaryKey = {};
      Map<String, bool> isForeignKey = {};
      Map<String, bool> isOtherKey = {};
      for (var col in pragma) {
        cols.add(col['name']);
        types[col['name']] = col['type'] ?? '';
        isBlob[col['name']] = col['type']?.toLowerCase() == 'blob';
        isProtected[col['name']] = col['type']?.toLowerCase() == 'protected';
        isPrimaryKey[col['name']] = col['pk'] == 1;
        isForeignKey[col['name']] = col['name'].endsWith(
          '_uuid',
        ); // Optional: falls du FK-Info hast
        isOtherKey[col['name']] = col['name'].endsWith(
          '_id',
        ); // Optional: falls du andere Key-Info hast
        if (col['pk'] == 1) {
          pkColumn = col['name']; // Merken für Updates
        }
      }

      setState(() {
        _columns = cols;
        _columnTypes = {
          for (int i = 0; i < cols.length; i++) cols[i]: types[cols[i]] ?? '',
        };
        _columnIsBlob = {
          for (int i = 0; i < cols.length; i++)
            cols[i]: isBlob[cols[i]] ?? false,
        };
        _columnIsProtected = {
          for (int i = 0; i < cols.length; i++)
            cols[i]: isProtected[cols[i]] ?? false,
        };
        _columnIsPrimaryKey = {
          for (int i = 0; i < cols.length; i++)
            cols[i]: isPrimaryKey[cols[i]] ?? false,
        };
        _columnIsForeignKey = {
          for (int i = 0; i < cols.length; i++)
            cols[i]: isForeignKey[cols[i]] ?? false,
        };
        _columnIsOtherKey = {
          for (int i = 0; i < cols.length; i++)
            cols[i]: isOtherKey[cols[i]] ?? false,
        };
        _primaryKey = pkColumn;
      });
    } catch (e) {
      _showSnackBar("Fehler beim Laden der Tabellen-Struktur: $e");
    }
  }

  // 2. Daten blockweise (Chunk Loading) nachladen
  Future<void> _loadMoreData() async {
    if (_isLoading || !_hasMore || _selectedTable == null) return;

    setState(() => _isLoading = true);

    try {
      if (_db == null) return;

      List<Map<String, dynamic>> newRows = await DatabaseService.instance
          .getExplorerTableRows(
            _selectedTable!,
            offset: _currentOffset,
            limit: _chunkSize,
          );

      setState(() {
        // Da sqflite-Maps read-only sind, machen wir sie editierbar (Modifiable Map)
        _rows.addAll(
          newRows.map((row) => Map<String, dynamic>.from(row)).toList(),
        );
        _currentOffset += _chunkSize;
        if (newRows.length < _chunkSize) {
          _hasMore = false;
        }
      });
    } catch (e) {
      _showSnackBar("Fehler beim Laden der Daten: $e");
    } finally {
      setState(() => _isLoading = false);
    }
  }

  // 3. Inline-Editierung in der DB speichern
  Future<void> _updateCell(
    String column,
    dynamic oldValue,
    int rowIndex,
  ) async {
    if (_primaryKey == null) {
      _showSnackBar(
        "Update nicht möglich: Kein Primary Key für diese Tabelle definiert!",
      );
      return;
    }

    final rowData = _rows[rowIndex];
    final pkValue = rowData[_primaryKey];

    if (pkValue == null) {
      _showSnackBar(
        "Update nicht möglich: Primary Key Wert dieser Zeile ist null!",
      );
      return;
    }

    TextEditingController controller = TextEditingController(
      text: oldValue?.toString() ?? "",
    );

    // Dialog für die Bearbeitung anzeigen
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text("Feld bearbeiten: $column"),
        content: TextField(
          controller: controller,
          decoration: const InputDecoration(labelText: "Neuer Wert"),
          keyboardType: oldValue is num
              ? TextInputType.number
              : TextInputType.text,
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text("Abbrechen"),
          ),
          ElevatedButton(
            onPressed: () async {
              dynamic newValue = controller.text;

              // Einfache Typkonvertierung basierend auf dem alten Wert
              if (oldValue is int) {
                newValue = int.tryParse(controller.text) ?? oldValue;
              } else if (oldValue is double) {
                newValue = double.tryParse(controller.text) ?? oldValue;
              }

              try {
                await DatabaseService.instance.updateExplorerTableRow(
                  _selectedTable!,
                  {column: newValue},
                  '$_primaryKey = ?',
                  [pkValue],
                );
                if (!mounted) return;
                setState(() {
                  _rows[rowIndex][column] = newValue;
                });

                Navigator.pop(context);
                _showSnackBar("Datenbank aktualisiert!");
              } catch (e) {
                _showSnackBar("Fehler beim Speichern: $e");
              }
            },
            child: const Text("Speichern"),
          ),
        ],
      ),
    );
  }

  void _showSnackBar(String message) {
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(SnackBar(content: Text(message)));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('SQLite DB Explorer'),
        backgroundColor: Colors.teal,
      ),
      body: SafeArea(
        child: Column(
          children: [
            // DROPDOWN-BEREICH
            Padding(
              padding: const EdgeInsets.all(12.0),
              child: Row(
                children: [
                  const Text(
                    "**Tabelle:** ",
                    style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(width: 10),
                  Expanded(
                    child: DropdownButton<String>(
                      value: _selectedTable,
                      isExpanded: true,
                      items: _tables.map((String table) {
                        return DropdownMenuItem<String>(
                          value: table,
                          child: Text(table),
                        );
                      }).toList(),
                      onChanged: (String? newValue) {
                        if (newValue != null) {
                          _resetAndLoadTableData(newValue);
                        }
                      },
                    ),
                  ),
                ],
              ),
            ),
            const Divider(height: 1),

            // TABELLEN-INHALT (Horizontal + Vertikal Scroll)
            Expanded(
              child: _columns.isEmpty
                  ? const Center(
                      child: Text("Keine Daten oder keine Tabelle ausgewählt"),
                    )
                  : SingleChildScrollView(
                      scrollDirection: Axis.vertical,
                      child: SingleChildScrollView(
                        scrollDirection: Axis.horizontal,
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            DataTable(
                              headingRowColor: WidgetStateProperty.all(
                                Colors.grey[200],
                              ),
                              columns: _columns.map((col) {
                                // Highlighte den Primary Key optisch
                                final isPk = _columnIsPrimaryKey[col] == true;
                                final isFk = _columnIsForeignKey[col] == true;
                                return DataColumn(
                                  label: Text(
                                    isPk
                                        ? "$col 🔑 TEXT"
                                        : isFk
                                        ? "$col 🔗 <${_columnTypes[col]}>"
                                        : "$col <${_columnTypes[col]}>",
                                    style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      color: isPk
                                          ? Colors.teal
                                          : isFk
                                          ? Colors.teal.shade900
                                          : Colors.black,
                                    ),
                                  ),
                                );
                              }).toList(),
                              rows: List.generate(_rows.length, (rowIndex) {
                                final rowData = _rows[rowIndex];
                                Uint8List? bytes;
                                Widget? imageWidget;
                                return DataRow(
                                  cells: _columns.map((colName) {
                                    final isBlob =
                                        _columnIsBlob[colName] == true;
                                    final isProtected =
                                        _columnIsProtected[colName] == true;
                                    final isPrimaryKey =
                                        _columnIsPrimaryKey[colName] == true;
                                    final isForeignKey =
                                        _columnIsForeignKey[colName] == true;

                                    final isOtherKey =
                                        _columnIsOtherKey[colName] == true;
                                    if (isBlob) {
                                      bytes = rowData[colName];
                                      try {
                                        if (bytes != null &&
                                            bytes!.isNotEmpty) {
                                          imageWidget = Image.memory(
                                            bytes!,
                                            width: 80,
                                            height: 45,
                                            fit: BoxFit.contain,
                                          );
                                        } else {
                                          imageWidget = const Icon(
                                            Icons.broken_image,
                                          );
                                        }
                                      } catch (e) {
                                        imageWidget = const Icon(Icons.error);
                                      }
                                    }
                                    final cellValue = isBlob
                                        ? "<BLOB>"
                                        : rowData[colName];

                                    return DataCell(
                                      !isBlob
                                          ? Text(
                                              cellValue?.toString() ?? 'NULL',
                                              style: TextStyle(
                                                fontWeight: isPrimaryKey
                                                    ? FontWeight.bold
                                                    : FontWeight.normal,
                                                fontStyle:
                                                    cellValue == null ||
                                                        isProtected ||
                                                        isPrimaryKey ||
                                                        isBlob
                                                    ? FontStyle.italic
                                                    : isForeignKey
                                                    ? FontStyle.italic
                                                    : isOtherKey
                                                    ? FontStyle.italic
                                                    : FontStyle.normal,
                                                color:
                                                    cellValue == null ||
                                                        isProtected ||
                                                        isPrimaryKey ||
                                                        isBlob
                                                    ? Colors.green
                                                    : isForeignKey
                                                    ? Colors.teal.shade500
                                                    : isOtherKey
                                                    ? Colors.green.shade900
                                                    : Colors.black,
                                              ),
                                            )
                                          : ClipRRect(
                                              borderRadius:
                                                  BorderRadius.circular(6),
                                              child:
                                                  imageWidget ??
                                                  const Icon(
                                                    Icons.broken_image,
                                                  ),
                                            ),
                                      showEditIcon:
                                          !isPrimaryKey &&
                                          !isBlob &&
                                          !isProtected,

                                      onTap:
                                          !isPrimaryKey &&
                                              !isBlob &&
                                              !isProtected
                                          ? () => _updateCell(
                                              colName,
                                              cellValue,
                                              rowIndex,
                                            )
                                          : null,
                                    );
                                  }).toList(),
                                );
                              }),
                            ),

                            // CHUNK LOADER BUTTONS
                            Padding(
                              padding: const EdgeInsets.all(16.0),
                              child: Row(
                                children: [
                                  if (_hasMore)
                                    ElevatedButton.icon(
                                      onPressed: _isLoading
                                          ? null
                                          : _loadMoreData,
                                      icon: _isLoading
                                          ? const SizedBox(
                                              width: 16,
                                              height: 16,
                                              child: CircularProgressIndicator(
                                                strokeWidth: 2,
                                              ),
                                            )
                                          : const Icon(Icons.arrow_downward),
                                      label: const Text("Mehr Zeilen laden..."),
                                    )
                                  else
                                    const Text(
                                      "--- Ende der Tabelle erreicht ---",
                                      style: TextStyle(color: Colors.grey),
                                    ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
            ),
          ],
        ),
      ),
    );
  }
}
